# Generated by Django 5.2.14 on 2026-09-27 01:49

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSpecialCommercialDate',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Evento Comercial')),
                ('slug', models.SlugField(blank=True, max_length=160, verbose_name='Slug Identificador')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción / Sugerencia de Promoción')),
                ('month', models.PositiveSmallIntegerField(help_text='Mes del evento (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('day', models.PositiveSmallIntegerField(help_text='Día del evento (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día')),
                ('days_in_advance', models.PositiveSmallIntegerField(default=15, help_text='Días de anticipación para emitir la alerta al administrador', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Días de Anticipación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_notified_year', models.PositiveIntegerField(blank=True, help_text='Año en el que se emitió la última alerta para evitar duplicados en el mismo ciclo', null=True, verbose_name='Último Año Notificado')),
                ('suggested_strategy', models.CharField(blank=True, default='', help_text='Ej. Combos de cocina, Descuento 20% en pantallas', max_length=200, verbose_name='Estrategia Comercial Sugerida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Temporada Comercial Especial',
                'verbose_name_plural': 'historical Temporadas Comerciales Especiales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SpecialCommercialDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Evento Comercial')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug Identificador')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción / Sugerencia de Promoción')),
                ('month', models.PositiveSmallIntegerField(help_text='Mes del evento (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('day', models.PositiveSmallIntegerField(help_text='Día del evento (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día')),
                ('days_in_advance', models.PositiveSmallIntegerField(default=15, help_text='Días de anticipación para emitir la alerta al administrador', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Días de Anticipación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_notified_year', models.PositiveIntegerField(blank=True, help_text='Año en el que se emitió la última alerta para evitar duplicados en el mismo ciclo', null=True, verbose_name='Último Año Notificado')),
                ('suggested_strategy', models.CharField(blank=True, default='', help_text='Ej. Combos de cocina, Descuento 20% en pantallas', max_length=200, verbose_name='Estrategia Comercial Sugerida')),
            ],
            options={
                'verbose_name': 'Temporada Comercial Especial',
                'verbose_name_plural': 'Temporadas Comerciales Especiales',
                'ordering': ['month', 'day'],
                'indexes': [models.Index(fields=['month', 'day'], name='notificatio_month_7ab46c_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_3a5208_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommercialEventAlert',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('event_type', models.CharField(choices=[('commercial_season', 'Temporada Comercial'), ('product_stock', 'Alerta de Inventario'), ('promotion_event', 'Evento de Promoción'), ('system_alert', 'Alerta del Sistema'), ('custom', 'Personalizada')], db_index=True, default='commercial_season', max_length=50, verbose_name='Tipo de Evento')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Alerta')),
                ('message', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('event_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año del Evento')),
                ('days_until_event', models.IntegerField(blank=True, null=True, verbose_name='Días Restantes al Emitir')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Enviado a Telegram')),
                ('telegram_error', models.TextField(blank=True, null=True, verbose_name='Detalle de Error de Telegram')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Leída en Panel Web')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos Adicionales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('commercial_date', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notifications.specialcommercialdate', verbose_name='Temporada Comercial Relacionada')),
            ],
            options={
                'verbose_name': 'historical Alerta de Notificación',
                'verbose_name_plural': 'historical Alertas de Notificaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CommercialEventAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('event_type', models.CharField(choices=[('commercial_season', 'Temporada Comercial'), ('product_stock', 'Alerta de Inventario'), ('promotion_event', 'Evento de Promoción'), ('system_alert', 'Alerta del Sistema'), ('custom', 'Personalizada')], db_index=True, default='commercial_season', max_length=50, verbose_name='Tipo de Evento')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Alerta')),
                ('message', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('event_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año del Evento')),
                ('days_until_event', models.IntegerField(blank=True, null=True, verbose_name='Días Restantes al Emitir')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Enviado a Telegram')),
                ('telegram_error', models.TextField(blank=True, null=True, verbose_name='Detalle de Error de Telegram')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Leída en Panel Web')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos Adicionales')),
                ('commercial_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='notifications.specialcommercialdate', verbose_name='Temporada Comercial Relacionada')),
            ],
            options={
                'verbose_name': 'Alerta de Notificación',
                'verbose_name_plural': 'Alertas de Notificaciones',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['is_read'], name='notificatio_is_read_250acd_idx'), models.Index(fields=['event_type'], name='notificatio_event_t_5c8396_idx'), models.Index(fields=['created_at'], name='notificatio_created_ef1bbc_idx')],
            },
        ),
    ]
