# Generated by Django 5.2.14 on 2026-08-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producttype_historicalproducttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='is_feature_product',
            field=models.BooleanField(default=False, verbose_name='Producto Destacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_feature_product',
            field=models.BooleanField(default=False, verbose_name='Producto Destacado'),
        ),
    ]
