# Generated by Django 5.2.14 on 2026-08-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_historicalproduct_is_feature_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['product_type_name'], 'verbose_name': 'Tipo de Producto', 'verbose_name_plural': 'Tipos de Productos'},
        ),
        migrations.RenameField(
            model_name='historicalproducttype',
            old_name='name',
            new_name='product_type_name',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='name',
            new_name='product_type_name',
        ),
        migrations.AddField(
            model_name='historicalproducttype',
            name='product_type_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen del Tipo'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='product_type_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_types/', verbose_name='Imagen del Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='depth_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profundo (cm)'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alto (cm)'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='security',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Seguridad'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profundo (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Alto (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='security',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Seguridad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ancho (cm)'),
        ),
    ]
