# Generated by Django 5.2.14 on 2026-08-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_historicalproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductimage',
            name='color_name',
            field=models.CharField(blank=True, help_text='Nombre del color asociado a la imagen (ej. Rojo, Azul, Verde)', max_length=100, null=True, verbose_name='Nombre del Color'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, help_text='Nombre del color asociado a la imagen (ej. Rojo, Azul, Verde)', max_length=100, null=True, verbose_name='Nombre del Color'),
        ),
    ]
