# Generated by Django 5.2.14 on 2026-08-19 14:40

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_historicalproductimage_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='product_video',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Video del Producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to=apps.product.models.rename_video_upload_to, verbose_name='Video del Producto'),
        ),
    ]
