# Generated by Django 5.2.14 on 2026-08-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproductcolorimage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Color de Producto', 'verbose_name_plural': 'historical Colores de los Productos'},
        ),
        migrations.AlterModelOptions(
            name='productangleimage',
            options={'ordering': ['id'], 'verbose_name': 'Ángulo de Producto', 'verbose_name_plural': 'Ángulos de Productos'},
        ),
        migrations.AlterModelOptions(
            name='productcolorimage',
            options={'verbose_name': 'Color de Producto', 'verbose_name_plural': 'Colores de los Productos'},
        ),
        migrations.RemoveField(
            model_name='historicalproductangleimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productangleimage',
            name='order',
        ),
    ]
