# Generated by Django 5.2.14 on 2026-08-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_historicalproductcolorimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='product.product', verbose_name='Producto'),
        ),
    ]
