# Generated by Django 5.2.14 on 2026-09-01 02:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productcolorimage_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='capacity',
            field=models.CharField(blank=True, help_text='Ej. 1.5L, 500GB, 12kg, 60L', max_length=100, null=True, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='ranking_score',
            field=models.FloatField(default=0.0, verbose_name='Score de Ranking'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Score de Sentimiento'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Vistas'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='voltage',
            field=models.CharField(blank=True, help_text='Ej. 110V, 220V, 110V/220V', max_length=50, null=True, verbose_name='Voltaje'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='weight_type',
            field=models.CharField(blank=True, help_text='Ej. Neto, Bruto, Embalado', max_length=100, null=True, verbose_name='Tipo de Peso / Clasificación'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, help_text='Ej. 1.5L, 500GB, 12kg, 60L', max_length=100, null=True, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='product',
            name='ranking_score',
            field=models.FloatField(default=0.0, verbose_name='Score de Ranking'),
        ),
        migrations.AddField(
            model_name='product',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Score de Sentimiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Vistas'),
        ),
        migrations.AddField(
            model_name='product',
            name='voltage',
            field=models.CharField(blank=True, help_text='Ej. 110V, 220V, 110V/220V', max_length=50, null=True, verbose_name='Voltaje'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_type',
            field=models.CharField(blank=True, help_text='Ej. Neto, Bruto, Embalado', max_length=100, null=True, verbose_name='Tipo de Peso / Clasificación'),
        ),
        migrations.CreateModel(
            name='HistoricalProductFeature',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('feature_name', models.CharField(help_text='Ej. Material, Garantía, Eficiencia Energética', max_length=150, verbose_name='Nombre de la Característica')),
                ('feature_value', models.CharField(help_text='Ej. Acero Inoxidable, 1 Año, A++', max_length=255, verbose_name='Valor de la Característica')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'historical Característica de Producto',
                'verbose_name_plural': 'historical Características de Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductReview',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positivo'), ('neutral', 'Neutral'), ('negative', 'Negativo')], default='neutral', max_length=10, verbose_name='Etiqueta de Sentimiento')),
                ('sentiment_confidence', models.FloatField(default=0.0, verbose_name='Confianza del Sentimiento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'historical Reseña de Producto',
                'verbose_name_plural': 'historical Reseñas de Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductViewLog',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'historical Registro de Vista',
                'verbose_name_plural': 'historical Registros de Vistas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('feature_name', models.CharField(help_text='Ej. Material, Garantía, Eficiencia Energética', max_length=150, verbose_name='Nombre de la Característica')),
                ('feature_value', models.CharField(help_text='Ej. Acero Inoxidable, 1 Año, A++', max_length=255, verbose_name='Valor de la Característica')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Característica de Producto',
                'verbose_name_plural': 'Características de Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positivo'), ('neutral', 'Neutral'), ('negative', 'Negativo')], default='neutral', max_length=10, verbose_name='Etiqueta de Sentimiento')),
                ('sentiment_confidence', models.FloatField(default=0.0, verbose_name='Confianza del Sentimiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Reseña de Producto',
                'verbose_name_plural': 'Reseñas de Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductViewLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Registro de Vista',
                'verbose_name_plural': 'Registros de Vistas',
                'ordering': ['-created_at'],
            },
        ),
    ]
