# Generated by Django 5.2.14 on 2026-09-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_historicalproduct_brand_historicalproduct_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='HistoricalProductType',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
